substrate-developer-hub/substrate-node-template

substrate-node-rename.sh

- Change file permissions to execute script.

Add execute permission to rename script

---

Cargo.lock
node/Cargo.toml
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs

Closes #35
Thanks to @brenzi for the work he did on #36 I copied a lot of it :pray:

Update to 2.0.0-alpha.7

---

Cargo.lock
README.md
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs

PR to merge @danforbes's update to alpha.8

Upgrade to Substrate v2.0.0-alpha.8

---

Cargo.lock
README.md
node/Cargo.toml
node/src/lib.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs

Please note the changes I made to the `README`. cc @jeluard :cartwheeling:

Upgrade to v2.0.0-rc4

---

.github/ISSUE_TEMPLATE/ask-a-question.md
.github/ISSUE_TEMPLATE/report-a-bug.md
.github/ISSUE_TEMPLATE/suggest-a-feature.md

- Report a Bug
- Suggest a Feature
- Ask a Question
cc @krichard410

Create Issue templates

---

node/src/service.rs

Backport paritytech/substrate#7014
Closes #80

Fix bug where the wrong import queue was used in service

---

rust-toolchain

Thank you @TriplEight :pray: 
Closes #95

Update toolchain file to be compatible with paritytech/ci-linux Docker

---

shell.nix

Also fixed error when using macos.
https://github.com/paritytech/substrate/pull/7376

Nix shell sync with Substrate

---

Cargo.toml

this will make adding and renaming pallets easier

include all (potential) pallets in Cargo workspace

---

doc/rust-setup.md

Add Fedora/RHEL/CentOS Installation details

Add Fedora/RHEL/CentOS

---

README.md

https://github.com/paritytech/substrate/pull/9476/ (now merged) - so the upstream substrate README includes this.

Add a matrix chat badge to the README

---

.envrc
.gitignore
Cargo.lock
Cargo.toml
README.md
node/Cargo.toml
node/build.rs
node/src/chain_spec.rs
node/src/cli.rs
node/src/command.rs
node/src/main.rs
node/src/rpc.rs
node/src/service.rs
pallets/kitties/Cargo.toml
pallets/kitties/src/lib.rs
pallets/kitties/src/mock.rs
pallets/kitties/src/tests.rs
pallets/template/Cargo.toml
pallets/template/src/benchmarking.rs
pallets/template/src/lib.rs
pallets/template/src/mock.rs
pallets/template/src/tests.rs
runtime/Cargo.toml
runtime/build.rs
runtime/src/lib.rs
runtime/types.json
rustfmt.toml
scripts/docker_run.sh
scripts/init.sh
shell.nix

@sacha-l
I updated the Kitty Tutorial to be based on `v3.0.0+monthly-2021-08`. This will cause a lot of changes when looking at the code diff, but the major changes are mostly in `pallets/kitties/src/lib.rs`.
Major changes: 
- Simplified to use only 3 storage pieces.
- Using **BoundedVec** for storing what kitties are owned by which user. The length of the BoundedVec, `MaxKittyOwned`, is passed in from runtime.
- Having **Currency** type in Config trait, and is passed in from runtime. It pretty much do what `Balance` allowed before, but also support checking user [`free_balance()`](https://substrate.dev/rustdocs/latest/frame_support/traits/tokens/currency/trait.Currency.html#tymethod.free_balance) and [`transfer()`](https://substrate.dev/rustdocs/latest/frame_support/traits/tokens/currency …

Kitties Update

---

shell.nix

Update nightly toolchain to 2021-06-17

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/benchmarking.rs
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Update to `monthly-2021-11`

---

README.md

README: Persistent state fix

---

Cargo.lock

cargo update -p sc-cli

---

runtime/src/lib.rs

https://github.com/paritytech/substrate/pull/10735/

add zero check

---

runtime/src/lib.rs

Reverts #301 
Need Polkadot 0.9.16 or above for this to work, this is not yet released.

revert zero

---

Cargo.lock
node/Cargo.toml

update use all features = ["wasmtime"] that can, missed in #313

`wasmtime`

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Update to polkadot-v0.9.18

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/command_helper.rs
node/src/main.rs
node/src/service.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

- command helper for benchmarks
- try runtime updates
- clap bump

Update to Polkadot v0.9.19 from upstream

---

docs/rust-setup.md

In order to successfully build the template, we need to install the make tool which can be done independently. However, it is recommended to install a commonly needed essential package.

Additional package needed for Debian/Ubuntu/WSL

---

Cargo.lock
README.md
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

Release info: https://github.com/paritytech/polkadot/releases/tag/v0.9.25

Update to polkadot-v0.9.25

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Polkadot release found here:
- https://github.com/paritytech/polkadot/releases/tag/v0.9.26

Update to polkadot-v0.9.26

---

Cargo.lock
README.md
docs/rust-setup.md
node/Cargo.toml
pallets/template/Cargo.toml
pallets/template/src/lib.rs
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.28

Auto-Update substrate-node-template from polkadot-v0.9.28

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.29

Auto-Update substrate-node-template from polkadot-v0.9.29

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.31

Auto-Update substrate-node-template from polkadot-v0.9.31

---

.github/workflows/check.yml

Current GHA is broken: `protoc` is required. PR fixes this

[ci] fix check GHA

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

Auto-Update substrate-node-template from polkadot-v0.9.32

Auto-Update substrate-node-template from polkadot-v0.9.32

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.35

Auto-Update substrate-node-template from polkadot-v0.9.35

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.36

Auto-Update substrate-node-template from polkadot-v0.9.36

---

Cargo.lock
node/Cargo.toml
node/src/benchmarking.rs
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/build.rs
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.37

Auto-Update substrate-node-template from polkadot-v0.9.37

---

Cargo.lock
README.md
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Auto-Update substrate-node-template from polkadot-v0.9.40

Auto-Update substrate-node-template from polkadot-v0.9.40
