Cargo.lock
Cargo.toml
README.md
runtime/Cargo.toml
runtime/build.rs
runtime/src/lib.rs
runtime/src/template.rs
scripts/init.sh
src/chain_spec.rs
src/cli.rs
src/service.rs

This updates to the latest version of the Substrate Node Template, which uses AuRa + Grandpa rather than BABE + Grandpa.
Waiting for @JoshOrndorff  to merge

Update to `d1cd01c74`

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

This PR is basically a routine update of the node template.
In addition to running the release script as described in the readme, it also points the dependencies to crates.io rather than github.

Update node template to alpha 5

---

build.rs

This PR deletes a single `build.rs` file from the root. That file was used before the node template was restructured into `node`, `runtime`, and `pallets` directories. The new home for this file is `node/build.rs` so this one can be safely deleted.

Delete outdated build.rs

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

If merged, it requires to push the tag to this commit.
Fixes incorrect alpha.7 dependencies.

alpha.6 to github

---

.gitignore
README.md
docker-compose.yml
scripts/docker_run.sh

I recently need to help solve the variance of platforms when developing on Substrate.
Docker is still the first choice when dealing with this situation. 
It would be good to know how are we going to support different platforms in the long term.
This change works in my MacOS, but haven't tested it in other platforms.

Use docker to setup a local dev chain 

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build-push-template.yml
.vscode/tasks.json
README.md

This adds the necessary files so that this repository is accessible as a playground template: Note that most files are standard VSCode files.
The GH actions file triggers and changes to the `master` branch and will:
* build a standalone Docker image
* publish it to [dockerhub](https://hub.docker.com/)
* update the `devcontainer.json` (see [Remote containers](https://code.visualstudio.com/docs/remote/containers))
* trigger the remote build and template inclusion in [substrate-playground](https://github.com/paritytech/substrate-playground/)
The following secrets will have to be defined:
* `DOCKER_USERNAME` and `DOCKER_PASSWORD` to push the image to dockerhub (values will depend on the chosen docker image org)
* `REPO_ACCESS_TOKEN` a …

Add some playground love

---

README.md
docker-compose.yml
rust-toolchain

Architecture specific toolchains are [not allowed](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) in this file. We can assume that stable is the default toolchain and should not dictate with which toolchain the user builds the client. Also this breaks under macOS.
We are only interested with which toolchain the runtime is build. For this we should set the `WASM_BUILD_TOOLCHAIN` variable.

Remove rust-toolchain file

---

runtime/Cargo.toml

1.0 wasm-builder-runner is not compatible with 2.0 wasm-builder https://github.com/paritytech/substrate/pull/7283#issuecomment-705824314
and we are using https://github.com/substrate-developer-hub/substrate-node-template/blob/5785c8d71da7882abf04748bf1dc61974638a922/runtime/build.rs#L6

Bump wasm-builder-runner

---

runtime/src/lib.rs
runtime/src/multiaddress.rs

This PR is a quality of life improvement for developers and Jaco who manages custom types.
With this PR, we are patching in the Multiaddress update from Substrate master that was not included in v2.0.1.
This will make it so that the Polkadot JS Apps can by default use the Multiaddress format, which is what we will be using across Polkadot, Kusama, and many other parachain teams which have already switched.
When the node template is updated again to the latest master, this file can simply be deleted and directly replaced with what is in `sp_runtime::multiadress`.
cc @jacogr

Patch Multiaddress Into Substrate Node Template

---

README.md

Addresses [#977](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/977).
This adds a way for new developers to get started with Playground if they prefer.

Include Playground link in Node Template README

---

README.md
runtime/types.json

@sacha-l @NukeManDan 
Adding instructions on the custom-types. Otherwise the Polkadot-JS Apps cannot decode the account data correctly from Substrate runtime.

Added instructions for custom-types

---

runtime/src/lib.rs

This commit removes the `AccountIndex` from the runtime/src/lib.rs as the `AccountIndex` type is typically used to configure the Indices pallet (https://substrate.dev/rustdocs/v3.0.0/pallet_indices/trait.Config.html) which is not used by the node template, so there is no point to include it.

Remove AccountIndex from runtime

---

README.md
scripts/docker_run.sh

The docker-compose.yml file binds a volume from ./.local path but if the path does not exist it fails (e.g. a fresh clone from this repo will fail to run docker). Changes are made to make docker_run.sh to make the directory if it does not exist.

fix missing docker-compose volume source (./.local)

---

.envrc
shell.nix

- envrc: made lorri optional
- shell.nix: added RUST_SRC_PATH, so rust-analyzer works out of the box
Lorri is not ubiquitous to every Nix user, so I made it optional. Also,
it's direnv command provides all the env you need, so `use_nix` was breaking
the point of using lorri as a background builder.
RUST_SRC_PATH is self-explanatory, and is needed for rust-analyzer to provide
code completion.

Minor Nix environent tweaks

---

node/src/chain_spec.rs
node/src/cli.rs
node/src/command.rs
node/src/lib.rs
node/src/rpc.rs
node/src/service.rs
pallets/template/src/benchmarking.rs
pallets/template/src/lib.rs
pallets/template/src/mock.rs
pallets/template/src/tests.rs
runtime/src/lib.rs
rustfmt.toml

Until updated automatically (https://github.com/paritytech/substrate/issues/9386) this PR introduces the same rustfmt.toml as substrate manually. I have also run `cargo +nightly fmt` on the whole repo here, hence the changes in files.
Note: Using "format on save" with the `settings.json` found here for rust-analyzer + VSCode works to automate this process.
"rust-analyzer.rustfmt.overrideCommand": [
"rustup",
"run",
"nightly",
"--",
"rustfmt"
],

Add rustfmt.toml, run `cargo +nightly fmt`

---

Cargo.lock
README.md
node/Cargo.toml
node/src/command.rs
node/src/rpc.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/benchmarking.rs
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs
scripts/docker_run.sh

Follows guide https://github.com/paritytech/substrate/blob/master/docs/node-template-release.md
Preserves README with edits for this template. 
I have updated the cargo files to include the monthly version correctly, and cleaned them up a bit for easier navigation.
Built with:
```bash
$ rustup show active-toolchain --verbose
stable-x86_64-unknown-linux-gnu (default)
rustc 1.54.0 (a178d0322 2021-07-26)
$ rustup +nightly show active-toolchain --verbose
nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.56.0-nightly (4e282795d 2021-07-31)
```
Tested to [work with the FE template](https://github.com/substrate-developer-hub/substrate-front-end-template/issues/188)

Update to substrate `monthly-2021-08`

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

New branch upstream to hold this (temporary) tag to have the whole build use 2021
https://github.com/paritytech/substrate/releases/tag/monthly-2021-11-1

update rust 2021

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

Upstream will now ALWAYS be https://github.com/paritytech/substrate/releases/tag/devhub%2Flatest
and we move the `latest` tag here on each DRAFT release we tag and E2E test for the devhub.

Move to use `devhub/latest` tag upstream

---

node/Cargo.toml
node/src/chain_spec.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Built on Ubuntu 20.04 LST:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
rustc 1.59.0-nightly (e2116acae 2021-12-05)
```
All changes from upstream: https://github.com/paritytech/substrate/tree/monthly-2021-12/bin/node-template

Update to `monthly-2021-12`

---

Cargo.lock
README.md
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Changes from Substrate upstream `polkadot-v0.9.15-1`
Use 1 line deps
use `devhub/latest` tag for deps
Use ONLY 4.0.0-dev deps for sp-core and sp-std and sp-runtime (upstream master is ahead)
Confirmed to build and run on Ubuntu 20.04 LTS with 
```
rustc 1.58.0 (02072b482 2022-01-11)
rustc 1.60.0-nightly (5e57faa78 2022-01-19)
```

Update `devhub/latest`  from Substrate upstream `polkadot-v0.9.15-1`

---

Cargo.lock
README.md
docs/rust-setup.md
node/Cargo.toml
node/src/chain_spec.rs
node/src/cli.rs
node/src/service.rs
pallets/template/Cargo.toml
pallets/template/src/mock.rs
runtime/Cargo.toml
runtime/src/lib.rs

Update to `polkadot-v.0.9.17`

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
pallets/template/Cargo.toml
runtime/Cargo.toml

- new CLI commands for convenience
Tested with Ubuntu 20.04 LTS
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
rustc 1.62.0-nightly (e1b71feb5 2022-05-03)
```

Update to `polkdadot-v0.9.20` from upstream

---

Cargo.lock
node/Cargo.toml
pallets/template/Cargo.toml
runtime/Cargo.toml

manifest key "branch" has a space in all the cargo.toml files.  it causes the branch info disabled

remove space from manifest key  branch in all the cargo.toml files

---

.envrc
.gitignore

If you are a direnv user but you are **not** a nix user, you cannot use direnv within this project.
If you  have direnv installed, whenever you `cd` into the `substrate-node-template` it will error with:
```
direnv: error /substrate-node-template/.envrc is blocked. Run `direnv allow` to approve its content
```
However, if you are not a nix user you cannot `direnv allow` this file as then every time you `cd` into the directory you will receive a `nix-shell: command not found` error.
This effectively prevents a developer from using direnv on this project, as their only option to prevent errors is to `direnv block` the `.envrc` file.
It does not appear that nix is required to use the `substrate-node-template` so I would suggest that the configuration of a developer's preferred shell should …

Remove and ignore .envrc

---

Cargo.lock
Cargo.toml

ahash version 0.7.6 no longer works with latest version of rustc nightly because `stdsimd` features has been removed.
To fix it I updated ahash with the command:
```
cargo update ahash@0.7.6
```
This should fix the compilation https://github.com/substrate-developer-hub/substrate-docs/issues/2130

run cargo update ahash@0.7.6
